// Package relaye2e is the crux verification for the relay box design: it
// proves that a real phone client can reach a real Mac companion process
// THROUGH a real relay box, end to end, while the box itself only ever
// handles ciphertext on the wire.
//
// It splices together two existing test rigs rather than reinventing them:
//   - the phone-side protocol client from
//     internal/mobileapi/transport/server_test.go (pairing.Service +
//     transport.Server + the real contract/pairing/session handshake), and
//   - the relay plumbing from internal/relayclient/harness_test.go (a real
//     relaybox.Box with a recording phone-door listener that captures every
//     byte the box handled).
//
// Nothing here reimplements pairing or session cryptography: every crypto
// step calls the exported pairing.* / contract.* functions the production
// code uses.
package relaye2e

import (
	"bytes"
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net"
	"net/http"
	"sync"
	"testing"
	"time"

	"github.com/coder/websocket"
	"github.com/coder/websocket/wsjson"
	"github.com/codex-launcher/codex-launcher/companion/internal/mobileapi/contract"
	"github.com/codex-launcher/codex-launcher/companion/internal/mobileapi/transport"
	"github.com/codex-launcher/codex-launcher/companion/internal/pairing"
	"github.com/codex-launcher/codex-launcher/companion/internal/relaybox"
	"github.com/codex-launcher/codex-launcher/companion/internal/relayclient"
)

const relaySecret = "e2e-registration-secret"

// TestPhoneReachesCompanionThroughRelayBoxWithCiphertextOnly is the crux
// verification: a real phone client, talking to a real Mac companion
// (pairing.Service + transport.Server), with every byte routed through a
// real relaybox.Box, proves (a) the tunnel actually works end to end and
// (b) the box's view of the phone-door traffic is ciphertext only.
func TestPhoneReachesCompanionThroughRelayBoxWithCiphertextOnly(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	logger := slog.New(slog.NewTextHandler(io.Discard, nil))

	// --- 1. The box: a phone door (recorded) and a Mac door, both real. ---
	boxCert, err := relaybox.GenerateSelfSignedCertificate(rand.Reader, time.Now())
	if err != nil {
		t.Fatalf("generate box certificate: %v", err)
	}
	box, err := relaybox.New(relaySecret, boxCert, relaybox.WithLogger(logger))
	if err != nil {
		t.Fatalf("new box: %v", err)
	}
	macDoorListener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("listen mac door: %v", err)
	}
	rawPhoneDoorListener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("listen phone door: %v", err)
	}
	recorded := &recordedBytes{}
	phoneDoorListener := &recordingListener{inner: rawPhoneDoorListener, seen: recorded}
	boxSPKI := boxCert.Leaf.RawSubjectPublicKeyInfo

	macDoorDone := make(chan error, 1)
	phoneDoorDone := make(chan error, 1)
	go func() { macDoorDone <- box.ServeMacDoor(ctx, macDoorListener) }()
	go func() { phoneDoorDone <- box.ServePhoneDoor(ctx, phoneDoorListener) }()

	// --- 2. The real Mac companion: pairing.Service + transport.Server. ---
	pairingService, err := pairing.NewServiceWithLogger(ctx, pairing.NewMemoryStore(), rand.Reader, logger)
	if err != nil {
		t.Fatalf("new pairing service: %v", err)
	}
	macCert, err := pairingService.TLSCertificate(time.Now())
	if err != nil {
		t.Fatalf("mac tls certificate: %v", err)
	}
	macSPKI := macCert.Leaf.RawSubjectPublicKeyInfo

	// The unique marker proves a real round trip: it is generated by the
	// (stubbed) message handler, sent as a real "welcome" contract.Message
	// over the real transport.Server, through the box, to the real phone
	// client below. Its presence in the received welcome (assertion 2) and
	// its absence from the box's recorded bytes (assertion 3b) together
	// prove the box could not read it.
	markerBytes := make([]byte, 16)
	if _, err := rand.Read(markerBytes); err != nil {
		t.Fatalf("generate marker: %v", err)
	}
	marker := "E2E-WELCOME-MARKER-" + fmt.Sprintf("%x", markerBytes)

	handler := func(handlerCtx context.Context, sender transport.MessageSender, message contract.Message) error {
		if message.Type != "hello" {
			return nil
		}
		welcomeBody, err := json.Marshal(map[string]any{
			"sessionId":    marker,
			"capabilities": []string{},
			"limits": map[string]any{
				"maxJsonBytes":         262144,
				"maxAttachmentBytes":   20971520,
				"maxDeviceUploads":     2,
				"maxGlobalUploads":     4,
				"maxTemporaryBytes":    104857600,
				"uploadExpirySeconds":  900,
			},
		})
		if err != nil {
			return err
		}
		return sender.Send(handlerCtx, contract.Message{
			Version: contract.Version{Major: 1}, MessageID: "welcome-e2e", Sender: "companion", Type: "welcome",
			Body: welcomeBody,
		})
	}
	server, err := transport.NewServer(pairingService, handler, logger)
	if err != nil {
		t.Fatalf("new transport server: %v", err)
	}

	// --- 3. The Mac dials OUT through the box; it never binds inbound. ---
	relayListener, err := relayclient.Listen(ctx, relayclient.Config{
		BoxAddr:         macDoorListener.Addr().String(),
		Secret:          relaySecret,
		PinnedPublicKey: boxSPKI,
		Logger:          logger,
	})
	if err != nil {
		t.Fatalf("relayclient listen/register: %v", err)
	}
	serveDone := make(chan error, 1)
	go func() { serveDone <- server.Serve(ctx, relayListener, macCert) }()

	t.Cleanup(func() {
		cancel()
		// transport.Server.Serve and relayclient.Listener.Accept both select
		// on this same ctx.Done(): Serve's shutdown goroutine calls
		// httpServer.Shutdown() (which closes the listener), while Accept
		// independently returns ctx.Err() the instant ctx is cancelled. Which
		// one wins is a genuine, pre-existing race between those two
		// packages (observed under `go test -race -count=N`, unrelated to
		// this test's crux assertions, which all complete before shutdown
		// starts): sometimes Serve reports context.Canceled instead of
		// wrapping http.ErrServerClosed. That is a benign shutdown-ordering
		// outcome, not a tunnel failure, so it is tolerated here; any other
		// error still fails the test.
		if err := <-serveDone; err != nil && !errors.Is(err, context.Canceled) {
			t.Errorf("companion serve shutdown: %v", err)
		}
		// The box doors return nil once ctx is cancelled (which cleanup did
		// above), so any non-nil error here is a real shutdown fault, not the
		// benign cancellation outcome — surface it rather than silently
		// draining the channel.
		if err := <-macDoorDone; err != nil && !errors.Is(err, context.Canceled) {
			t.Errorf("box mac door shutdown: %v", err)
		}
		if err := <-phoneDoorDone; err != nil && !errors.Is(err, context.Canceled) {
			t.Errorf("box phone door shutdown: %v", err)
		}
	})

	// --- 4. The phone client: raw TCP to the box PHONE door, inner TLS pinned to the Mac cert. ---
	phoneHTTPClient := pinnedPhoneClient(rawPhoneDoorListener.Addr().String(), macSPKI)

	offer, err := pairingService.BeginPairing(pairing.PairingTarget{Host: "100.64.0.10", Port: 9443, Protocol: 1}, time.Now())
	if err != nil {
		t.Fatalf("begin pairing: %v", err)
	}
	devicePublicKey, devicePrivateKey, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("generate device key: %v", err)
	}
	pairRequest := pairing.PairRequest{
		Secret: offer.Secret, Host: offer.Target.Host, Port: offer.Target.Port, Protocol: offer.Target.Protocol,
		HostPublicKey: offer.HostPublicKey, DeviceID: "e2e-phone", DeviceName: "E2E Phone", DevicePublicKey: devicePublicKey,
	}
	pairRequest.Signature = ed25519.Sign(devicePrivateKey, pairing.PairingProofMessage(pairRequest))

	pairBody, err := json.Marshal(pairRequestWire{
		Secret: pairRequest.Secret, Host: pairRequest.Host, Port: pairRequest.Port, Protocol: pairRequest.Protocol,
		HostPublicKey: pairRequest.HostPublicKey, DeviceID: pairRequest.DeviceID, DeviceName: pairRequest.DeviceName,
		DevicePublicKey: base64.RawURLEncoding.EncodeToString(pairRequest.DevicePublicKey),
		Signature:       base64.RawURLEncoding.EncodeToString(pairRequest.Signature),
	})
	if err != nil {
		t.Fatalf("marshal pair request: %v", err)
	}

	// The URL host is irrelevant: phoneHTTPClient's DialContext always dials
	// the box's raw phone-door address regardless of what host appears here.
	//
	// This is the phone's FIRST contact, so it is the one request that can race
	// the Mac's registration: relayclient.Listen returns once the REGISTER line
	// has been written, but the box processes it asynchronously, leaving a small
	// window where a phone that dials in is (correctly) dropped with
	// no_control_line. A real phone simply reconnects; retrying the first
	// request here keeps the crux test deterministic under heavy parallel
	// -race load without weakening any assertion — a dropped attempt is a
	// transport error, never a wrong status or body. Once this POST succeeds
	// the control line is up and stays up, so the later websocket dial does not
	// need the same guard. The body is rebuilt each attempt because a
	// bytes.Reader is consumed by the first send.
	pairResponse := postThroughTunnelWithRetry(t, phoneHTTPClient, pairBody)
	defer pairResponse.Body.Close()
	if pairResponse.StatusCode != http.StatusCreated {
		responseBody, _ := io.ReadAll(pairResponse.Body)
		t.Fatalf("pair status = %d, body = %s (tunnel did not deliver a working pairing round trip)", pairResponse.StatusCode, responseBody)
	}
	var paired pairResponseWire
	if err := json.NewDecoder(pairResponse.Body).Decode(&paired); err != nil || paired.DeviceID != "e2e-phone" || paired.PairingGeneration == "" {
		t.Fatalf("pair response = %#v, error = %v", paired, err)
	}

	// --- 5. Session handshake over the same tunnel: challenge -> proof -> authenticated -> hello -> welcome. ---
	websocketURL := "wss://companion.invalid/v1/session?deviceId=e2e-phone&sessionId=session-e2e"
	connection, _, err := websocket.Dial(ctx, websocketURL, &websocket.DialOptions{HTTPClient: phoneHTTPClient})
	if err != nil {
		t.Fatalf("websocket dial through the relay tunnel: %v", err)
	}
	defer connection.CloseNow()

	var challengeWire sessionChallengeWire
	if err := wsjson.Read(ctx, connection, &challengeWire); err != nil {
		t.Fatalf("read session challenge: %v", err)
	}
	proof, err := challengeWire.toProof()
	if err != nil {
		t.Fatalf("decode session challenge: %v", err)
	}
	proof.Signature = signPhone(t, devicePrivateKey, pairing.SessionProofMessage(proof))
	if err := wsjson.Write(ctx, connection, sessionProofWireFrom(proof)); err != nil {
		t.Fatalf("write session proof: %v", err)
	}
	var authenticated authenticatedWire
	if err := wsjson.Read(ctx, connection, &authenticated); err != nil || authenticated.Type != "authenticated" || authenticated.DeviceID != "e2e-phone" {
		t.Fatalf("authenticated response = %#v, error = %v (session handshake did not complete through the tunnel)", authenticated, err)
	}

	hello := []byte(`{"version":{"major":1,"minor":0},"messageId":"m-hello-e2e","sender":"phone","type":"hello","body":{"clientInstanceId":"e2e-phone","supportedMajors":[1],"resume":{"mode":"no_local_state"}}}`)
	if err := connection.Write(ctx, websocket.MessageText, hello); err != nil {
		t.Fatalf("write hello: %v", err)
	}
	messageType, outbound, err := connection.Read(ctx)
	if err != nil || messageType != websocket.MessageText {
		t.Fatalf("read welcome through the tunnel: type = %v, error = %v (this means the tunnel did not deliver a real round trip)", messageType, err)
	}
	welcome, err := contract.DecodeText(outbound)
	if err != nil || welcome.Type != "welcome" || welcome.Sender != "companion" {
		t.Fatalf("decode welcome: %#v, error = %v", welcome, err)
	}
	if !bytes.Contains(welcome.Body, []byte(marker)) {
		t.Fatalf("welcome body does not contain the marker the companion sent: body = %s (tunnel is broken, not just unverified)", welcome.Body)
	}

	// --- 6. The proof: everything the box saw on the phone door. ---
	seen := recorded.snapshot()

	// 3a: the box actually handled real traffic.
	if len(seen) == 0 {
		t.Fatal("box recorded no bytes on the phone door")
	}

	// 3b: the marker — proven above to have crossed the wire all the way to
	// the phone in cleartext form inside the welcome message — never appears
	// in what the box saw. Because assertion 2 already proved the marker
	// really did cross the tunnel, its absence here is not a vacuous check:
	// it demonstrates the box's own copy of the bytes never contained it,
	// i.e. the inner TLS layer, not the box, is what delivered it.
	if bytes.Contains(seen, []byte(marker)) {
		t.Fatal("the box's recorded phone-door bytes contain the welcome marker in the clear: the box can read tunnel content")
	}

	// 3c: the pairing secret, sent inside the phone<->Mac TLS layer, must
	// never appear in the box's clear view either.
	if bytes.Contains(seen, []byte(offer.Secret)) {
		t.Fatal("the box's recorded phone-door bytes contain the pairing secret in the clear")
	}

	// 3d: the very first bytes the box saw on the phone door are a TLS
	// handshake record (0x16 0x03 = TLS ClientHello), not plaintext HTTP.
	if len(seen) < 2 || seen[0] != 0x16 || seen[1] != 0x03 {
		got := "too short"
		if len(seen) >= 2 {
			got = fmt.Sprintf("0x%02x 0x%02x", seen[0], seen[1])
		}
		t.Fatalf("first phone-door bytes = %s, want a TLS handshake record (0x16 0x03)", got)
	}
}

// pinnedPhoneClient returns an *http.Client that reaches the box's raw phone
// door over TCP and then speaks inner TLS pinned to the companion's leaf
// certificate SPKI — exactly like the real Android app: it never trusts a
// certificate authority, only the pinned key.
func pinnedPhoneClient(phoneDoorAddr string, pinnedMacSPKI []byte) *http.Client {
	dialPhoneDoor := func(dialCtx context.Context, _, _ string) (net.Conn, error) {
		var dialer net.Dialer
		return dialer.DialContext(dialCtx, "tcp", phoneDoorAddr)
	}
	tlsConfig := &tls.Config{
		MinVersion:         tls.VersionTLS13,
		InsecureSkipVerify: true,
		NextProtos:         []string{"http/1.1"},
	}
	tlsConfig.VerifyConnection = func(state tls.ConnectionState) error {
		if len(state.PeerCertificates) != 1 || !bytes.Equal(state.PeerCertificates[0].RawSubjectPublicKeyInfo, pinnedMacSPKI) {
			return x509.UnknownAuthorityError{}
		}
		return nil
	}
	transport := &http.Transport{DialContext: dialPhoneDoor, TLSClientConfig: tlsConfig}
	return &http.Client{Transport: transport, Timeout: 10 * time.Second}
}

// postThroughTunnelWithRetry issues the phone's first POST through the box,
// retrying briefly on a connection-level failure (the no_control_line startup
// window described at the call site). Each attempt gets a fresh body reader
// because http.Client consumes it. A dropped attempt only ever surfaces as a
// transport error here — never a wrong HTTP status or body — so retrying
// cannot mask a real tunnel failure.
func postThroughTunnelWithRetry(t *testing.T, client *http.Client, body []byte) *http.Response {
	t.Helper()
	deadline := time.Now().Add(5 * time.Second)
	for {
		resp, err := client.Post("https://companion.invalid/v1/pair", "application/json", bytes.NewReader(body))
		if err == nil {
			return resp
		}
		if time.Now().After(deadline) {
			t.Fatalf("POST /v1/pair through the relay tunnel failed after retries: %v", err)
		}
		time.Sleep(20 * time.Millisecond)
	}
}

func signPhone(t *testing.T, key ed25519.PrivateKey, message []byte) []byte {
	t.Helper()
	return ed25519.Sign(key, message)
}

// --- Wire shapes, copied field-for-field from the unexported types in
// internal/mobileapi/transport/session.go (pairRequestBody, pairResponseBody,
// sessionChallengeBody, sessionProofBody, authenticatedBody). This package
// cannot import those unexported types, so the JSON tags are re-declared
// here; the actual pairing/session cryptography is still done exclusively by
// calling pairing.* functions, never reimplemented.

type pairRequestWire struct {
	Secret          string `json:"secret"`
	Host            string `json:"host"`
	Port            int    `json:"port"`
	Protocol        int    `json:"protocol"`
	HostPublicKey   string `json:"hostPublicKey"`
	DeviceID        string `json:"deviceId"`
	DeviceName      string `json:"deviceName"`
	DevicePublicKey string `json:"devicePublicKey"`
	Signature       string `json:"signature"`
}

type pairResponseWire struct {
	DeviceID          string `json:"deviceId"`
	PairingGeneration string `json:"pairingGeneration"`
}

type sessionChallengeWire struct {
	DeviceID          string `json:"deviceId"`
	SessionID         string `json:"sessionId"`
	PairingGeneration string `json:"pairingGeneration"`
	Protocol          int    `json:"protocol"`
	HostPublicKey     string `json:"hostPublicKey"`
	Nonce             string `json:"nonce"`
	ExpiresAt         int64  `json:"expiresAt"`
	HostSignature     string `json:"hostSignature"`
}

type sessionProofWire struct {
	DeviceID          string `json:"deviceId"`
	SessionID         string `json:"sessionId"`
	PairingGeneration string `json:"pairingGeneration"`
	Protocol          int    `json:"protocol"`
	HostPublicKey     string `json:"hostPublicKey"`
	Nonce             string `json:"nonce"`
	ExpiresAt         int64  `json:"expiresAt"`
	HostSignature     string `json:"hostSignature"`
	Signature         string `json:"signature"`
}

type authenticatedWire struct {
	Type      string `json:"type"`
	DeviceID  string `json:"deviceId"`
	SessionID string `json:"sessionId"`
}

func (wire sessionChallengeWire) toProof() (pairing.SessionProof, error) {
	hostSignature, err := base64.RawURLEncoding.DecodeString(wire.HostSignature)
	if err != nil {
		return pairing.SessionProof{}, errors.New("invalid host signature encoding")
	}
	return pairing.SessionProof{
		DeviceID: wire.DeviceID, SessionID: wire.SessionID, PairingGeneration: wire.PairingGeneration, Protocol: wire.Protocol,
		HostPublicKey: wire.HostPublicKey, Nonce: wire.Nonce, ExpiresAt: time.Unix(wire.ExpiresAt, 0), HostSignature: hostSignature,
	}, nil
}

func sessionProofWireFrom(proof pairing.SessionProof) sessionProofWire {
	return sessionProofWire{
		DeviceID: proof.DeviceID, SessionID: proof.SessionID, PairingGeneration: proof.PairingGeneration, Protocol: proof.Protocol,
		HostPublicKey: proof.HostPublicKey, Nonce: proof.Nonce, ExpiresAt: proof.ExpiresAt.Unix(),
		HostSignature: base64.RawURLEncoding.EncodeToString(proof.HostSignature), Signature: base64.RawURLEncoding.EncodeToString(proof.Signature),
	}
}

// --- Relay-door recording, copied from internal/relayclient/harness_test.go
// (recordedBytes / recordingListener / recordingConn). This is the exact
// mechanism that captures what the box actually handled on the phone door,
// in both directions, so assertions 3a-3d are measuring real wire bytes.

type recordedBytes struct {
	mu  sync.Mutex
	buf bytes.Buffer
}

func (r *recordedBytes) append(p []byte) {
	r.mu.Lock()
	r.buf.Write(p)
	r.mu.Unlock()
}

func (r *recordedBytes) snapshot() []byte {
	r.mu.Lock()
	defer r.mu.Unlock()
	return append([]byte(nil), r.buf.Bytes()...)
}

type recordingListener struct {
	inner net.Listener
	seen  *recordedBytes
}

func (l *recordingListener) Accept() (net.Conn, error) {
	conn, err := l.inner.Accept()
	if err != nil {
		return nil, err
	}
	return &recordingConn{Conn: conn, seen: l.seen}, nil
}

func (l *recordingListener) Close() error   { return l.inner.Close() }
func (l *recordingListener) Addr() net.Addr { return l.inner.Addr() }

type recordingConn struct {
	net.Conn
	seen *recordedBytes
}

func (c *recordingConn) Read(p []byte) (int, error) {
	n, err := c.Conn.Read(p)
	if n > 0 {
		c.seen.append(p[:n])
	}
	return n, err
}

func (c *recordingConn) Write(p []byte) (int, error) {
	if len(p) > 0 {
		c.seen.append(p)
	}
	return c.Conn.Write(p)
}
